### ISSUE TITLE
Acquire cluster

### ISSUE THREAD

**Issue by clintkitson** [SuperKomputer/superkomputer.io#4]
When a cluster is acquired, the response to the user should be a configuation file that is populated with relevant information from the cluster.

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: {api}
  name: cluster
contexts:
- context:
    cluster: cluster
    namespace: {context}
    user: {username}
  name: cluster
current-context: cluster
kind: Config
preferences: {}
users:
- name: {username}
  user:
    password: {password}
    username: {username}
```
